# Page settings

baseurl = "/"
languageCode = "zh-cn"
title = "Kenny Yao"
theme = "orbit"
publishDir = "docs"
# googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "sitemap", "RSS"]

[params]

# Meta
description = "Kenny Yao's online resume."
author = "Kenny Yao"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Kenny Yao"
        tagline = "Full Stack Developer"
        avatar = "avatar.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: k@m.fish"
        title = "k@m.fish"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+8618501252333"
        title = "18501252333"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "http://blog.kenny.cc"
        title = "kenny.cc"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/blockhack"
        title = "github.com/blockhack"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/blockhack"
        title = "@blockhack"

        [[params.contact.list]]
        class = "instagram"
        icon = "fa-instagram"
        url = "//www.instagram.com/blockhacker"
        title = "@blockhacker"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MS in Electrical & Information Engineering"
        college = "Xidian University"
        dates = "2011 - 2014"

        [[params.education.list]]
        degree = "BS in Information Security"
        college = "Xidian University"
        dates = "2007 - 2011"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Chinese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Skilled"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Coding"

        [[params.interests.list]]
        interest = "Photography"

        [[params.interests.list]]
        interest = "Football"

        [[params.interests.list]]
        interest = "Travel"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Serial Entrepreneur, Former Hacker, Coding Addict.** Full Stack Developer and Lead Engineer at Xiang Xin(http://xiang.xin). Master’s degree at Xidian University major in network/system attack and defense. 6-plus years of engineering experience, 3-plus years of hands-on technical/product leadership experience, made me a seasoned developer as well as UX expert of product development."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Lead Developer & Co-Founder"
        dates = "2015 - Present"
        company = "Xiang Xin, Beijing"
        details = ""

        [[params.jobs.list]]
        position = "Lead Developer"
        dates = "2014 - 2015"
        company = "Che Mi, Beijing"
        details = ""

        [[params.jobs.list]]
        position = "Front End Software Engineer"
        dates = "2012 - 2014"
        company = "Baidu, Beijing"
        details = ""

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = ""

        [[params.projects.list]]
        title = "Xiang Xin"
        url = "http://xiang.xin"
        tagline = "Xiang Xin is a platform(website, app, webapp) offering more reliable, transparent, efficient trucking services for shippers. With the help of matching algorithms, we help drivers to find the most suitable works and increase their incomes."

        [[params.projects.list]]
        title = "Baidu Map"
        url = "https://map.baidu.com"
        tagline = "Including Baidu Map PC website, Mobile WebApp, Street View, UGC Platform, Statistical Platform."

        [[params.projects.list]]
        title = "Baidu Local Business Center"
        url = "http://nlbc.baidu.com"
        tagline = "Baidu Local Business Center is a website for users to manage their shops on Baidu Map."

        [[params.projects.list]]
        title = "Che Mi(offline)"
        url = ""
        tagline = "Che Mi is a community of auto aftermarket. Products Including a community website and some other tool apps concerning car services."

        [[params.projects.list]]
        title = "Cao Pan Ke(offline)"
        url = ""
        tagline = "A fintech project for high net worth individuals' asset allocation."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Golang"
        level = "95%"

        [[params.skills.list]]
        skill = "PHP"
        level = "95%"

        [[params.skills.list]]
        skill = "Front End"
        level = "95%"

        [[params.skills.list]]
        skill = "HTML & CSS"
        level = "95%"

        [[params.skills.list]]
        skill = "Database"
        level = "85%"

        [[params.skills.list]]
        skill = "Web Security"
        level = "85%"

        [[params.skills.list]]
        skill = "Python"
        level = "75%"

        [[params.skills.list]]
        skill = "R"
        level = "75%"

        [[params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "65%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
